version: '3'

services:
  wordpress:
    image: wordpress:latest
    container_name: My-contair
    ports:
     - "8090:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin123
      WORDPRESS_DB_NAME: mysql
    volumes:
      - wordpress_data:/var/www/html
    restart: always

  db:
   image: mysql:latest
   container_name : db
   ports:
      - "3306:90"
   environment:
     MYSQL_ROOT_PASSWORD: admin123
     MYSQL_DATABASE: mysql
     MYSQL_USER: admin
     MYSQL_PASSWORD: admin123
   volumes:
     - mysql_data:/var/lib/mysql
   restart: always

volumes:
  wordpress_data:
  mysql_data:
